name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente
  workflow_dispatch: # Permite execução manual

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Erlon335
          output: dist/snake.svg

      - name: Push Animation to Repository
        uses: EndBug/add-and-commit@v9
        with:
          message: "Atualiza animação da cobra"
          add: "dist/snake.svg"
